export const mockApps = [
  {
    id: "app-1",
    name: "FocusFlow - Pomodoro Timer",
    icon: "🍅",
    status: "Live",
    lastUpdated: "2026-03-20",
    revenue: 1245.50,
    downloads: 15420,
    rating: 4.8,
    reviews: 342,
    category: "Productivity",
    niche: "Time Management",
    projectedRevenue: 1500,
  },
  {
    id: "app-2",
    name: "Zenith - Sleep Sounds",
    icon: "🌙",
    status: "Live",
    lastUpdated: "2026-03-15",
    revenue: 890.20,
    downloads: 8900,
    rating: 4.6,
    reviews: 128,
    category: "Health & Fitness",
    niche: "Sleep & Meditation",
    projectedRevenue: 1000,
  },
  {
    id: "app-3",
    name: "PixelArt Maker",
    icon: "🎨",
    status: "Updating",
    lastUpdated: "2026-03-24",
    revenue: 450.00,
    downloads: 5200,
    rating: 4.2,
    reviews: 89,
    category: "Art & Design",
    niche: "Pixel Art",
    projectedRevenue: 600,
  },
  {
    id: "app-4",
    name: "CryptoTracker Pro",
    icon: "📈",
    status: "In Review",
    lastUpdated: "2026-03-25",
    revenue: 0,
    downloads: 0,
    rating: 0,
    reviews: 0,
    category: "Finance",
    niche: "Crypto Portfolio",
    projectedRevenue: 2000,
  },
  {
    id: "app-5",
    name: "RecipeGenie AI",
    icon: "🍳",
    status: "Draft",
    lastUpdated: "2026-03-24",
    revenue: 0,
    downloads: 0,
    rating: 0,
    reviews: 0,
    category: "Food & Drink",
    niche: "AI Cooking",
    projectedRevenue: 800,
  },
  {
    id: "app-6",
    name: "FitQuest RPG",
    icon: "⚔️",
    status: "In Process",
    lastUpdated: "2026-03-25",
    revenue: 0,
    downloads: 0,
    rating: 0,
    reviews: 0,
    category: "Health & Fitness",
    niche: "Gamified Fitness",
    projectedRevenue: 1200,
  }
]

export const revenueData = [
  { name: "Mar 1", revenue: 400 },
  { name: "Mar 5", revenue: 300 },
  { name: "Mar 10", revenue: 550 },
  { name: "Mar 15", revenue: 450 },
  { name: "Mar 20", revenue: 700 },
  { name: "Mar 25", revenue: 850 },
]

export const downloadsData = [
  { name: "Mar 1", downloads: 1200 },
  { name: "Mar 5", downloads: 900 },
  { name: "Mar 10", downloads: 1500 },
  { name: "Mar 15", downloads: 1100 },
  { name: "Mar 20", downloads: 2000 },
  { name: "Mar 25", downloads: 2400 },
]
